kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: 'solacetk-ui'
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi

---
kind: Service
apiVersion: v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/JRBowman/solace-toolkit.git
  labels:
    app: solacetk-ui
    app.kubernetes.io/component: solacetk-ui
    app.kubernetes.io/instance: solacetk-ui
    app.kubernetes.io/name: solacetk-ui
    app.openshift.io/runtime: angularjs
  name: solacetk-ui
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: solacetk-ui
    deploymentconfig: solacetk-ui
  sessionAffinity: None
  type: ClusterIP

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: solacetk-ui
    app.kubernetes.io/component: solacetk-ui
    app.kubernetes.io/instance: solacetk-ui
    app.kubernetes.io/name: solacetk-ui
    app.openshift.io/runtime: angularjs
  name: solacetk-ui
spec:
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: solacetk-ui
    weight: 100
  wildcardPolicy: None

---
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/JRBowman/solace-toolkit.git
  labels:
    app: solacetk-ui
    app.kubernetes.io/component: solacetk-ui
    app.kubernetes.io/instance: solacetk-ui
    app.kubernetes.io/name: solacetk-ui
    app.kubernetes.io/part-of: solacetk-dev
    app.openshift.io/runtime: angularjs
  name: solacetk-ui
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: solacetk-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: solacetk-ui
        deploymentconfig: solacetk-ui
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/demo-vm-ossm/solacetk-ui:latest
        imagePullPolicy: Always
        name: solacetk-ui
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
kind: Pipeline
apiVersion: tekton.dev/v1
metadata:
  name: solacetk-ui
spec:
  params:
    - default: 'https://github.com/JRBowman/solace-toolkit.git'
      name: GIT_REPO
      type: string
    - default: master
      name: GIT_REVISION
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/bowman-dev/solacetk-ui'
      name: IMAGE_NAME
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:681dc67d2aa1dbecbf65ecd229c8b181dae533bf14b07543c1aeead36aed2198'
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: BUILDER_IMAGE
          value: 'registry.redhat.io/rhel8/buildah@sha256:aac6629389db17e99894c5bee0da01d4c8065d11d8c6f6e1602f9484290baa70'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
    - name: openshift-client
      runAfter:
        - buildah
      taskRef:
        kind: ClusterTask
        name: openshift-client
      params:
        - name: SCRIPT
          value: oc rollout status deploy/solacetk-ui
        - name: VERSION
          value: latest
  workspaces:
    - name: workspace

---
kind: PipelineRun
apiVersion: tekton.dev/v1
metadata:
  annotations:
    chains.tekton.dev/signed: 'true'
  generateName: solacetk-ui-
  finalizers:
    - chains.tekton.dev/pipelinerun
  labels:
    tekton.dev/pipeline: solacetk-ui
spec:
  params:
    - name: GIT_REPO
      value: 'https://github.com/JRBowman/solace-toolkit.git'
    - name: GIT_REVISION
      value: master
    - name: IMAGE_NAME
      value: 'image-registry.openshift-image-registry.svc:5000/bowman-dev/solacetk-ui'
    - name: PATH_CONTEXT
      value: .
  pipelineRef:
    name: solacetk-ui
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: solacetk-ui
