apiVersion: v1
kind: Service
metadata:
  name: solacetk-api
spec:
  selector:
    vm.kubevirt.io/name: winserver-iis
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8081-tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
